version: '3.8'

services:
  todolist-api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: todolist-api
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env
    ports:
      - 8000:8000

  todolist-client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: todolist-client
    volumes:
      - ./client:/app
      - /app/node_modules
    env_file:
      - ./client/.env
    ports:
      - 3000:3000
      - 3010:3010

  todolist-db:
    image: postgres:14-alpine
    container_name: todolist-db
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: todolist
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - todolist-db-volume:/var/lib/postgresql/data
      - ./data:/docker-entrypoint-initdb.d

volumes:
  todolist-db-volume:
